name: Flutter macOS / iOS CI

on:
  push:
  pull_request:

jobs:
  macos-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Flutter doctor
        run: flutter doctor -v
      - name: Analyze
        run: |
          flutter pub get
          flutter analyze
      - name: Build iOS (no codesign)
        run: |
          if [ -d samples/q01_lifecycle ]; then
            cd samples/q01_lifecycle
            flutter pub get
            flutter build ios --no-codesign || true
            cd ../..
          fi
          if [ -d samples/q02_state_persistence ]; then
            cd samples/q02_state_persistence
            flutter pub get
            flutter build ios --no-codesign || true
            cd ../..
          fi
      - name: Run tests
        run: |
          if [ -d samples/q01_lifecycle ]; then (cd samples/q01_lifecycle && flutter test) || true; fi
          if [ -d samples/q02_state_persistence ]; then (cd samples/q02_state_persistence && flutter test) || true; fi
